sudo: false
language: ruby

rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true

before_install: gem update --remote bundler
install:
  - bundle install --retry=3
script:
  - bundle exec rake dummy:prepare
  - bundle exec rspec

addons:
  code_climate:
    repo_token: 9c938a047651a943393f0f52bfc1d03d71fce0f19bf0f8c1265033af9b09a56e
